name: CI
on:
  push:
  pull_request:

jobs:
  install-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Import smoke test
        run: >
          python -c "import importlib;
          [importlib.import_module(m) for m in ['pandas','numpy','streamlit','openpyxl']];
          print('Deps OK')"

